### ISSUE TITLE
radixconfig.yaml - Schedule jobs for environment

### ISSUE THREAD

**Issue by olems** [equinor/radix-platform#149]
It would be useful to be able to set an environment to build on a chron-style schedule instead of trigger on git commit, to enable nightly builds or regular test runs.

**Comment by emirgens** [comment]
Ref. Slack conversation.
Nightly builds? The Radix platform is design for continuous build, test and deploy, and a common way of doing software development.
However there may be cases that require such tasks as you describe.
We are in the progress of making a CLI (Rx) available, and this will probably be of help to you.
Anyway - if you are welcome to drop by and have a chat with the team, so that we can get a better understanding and can help you.

**Comment by olems** [comment]
It's not the most crucial feature but it's a common use case in other CI platforms. We've used it as the distinction between dev and test instances - dev is always the current head of the development branch while we want the test instance to be more predictable throughout the day so it only deploys nightly.

**Comment by emirgens** [comment]
Can be achieved using GitHub actions
