### ISSUE TITLE
Adding a configurable pre-deploy step

### ISSUE THREAD

**Issue by haakon-bouvet** [equinor/radix-platform#548]
**Is your feature request related to a problem? Please describe.**
We wish to ensure a successful entity framework migration of a database before deploying any pods, provided there is database changes. Should such a migration fail, we would not wish to deploy, or promote a pod to a new environment. Our database is hosted separately from our API, and our API does not have, nor should it have, the rights required to preform such an update.

**Describe the solution you'd like**
I would like to have a configurable pre-deploy step, that runs before a deploy/promote of a pod. What happens in this would not necessarily be an entity framework migration, but would rather be anything that needs to be completed successfully pre-deploy.

**Describe alternatives you've considered**
 - Running the migration as part of the API start up - this is not possible due to the API lacking the rights of running migrations.
 - Running the script as part during the docker build - this would prevent us from using the promote feature.
 - Running the script in the docker files entry point - this would potentially cause the API within pod not to respond to Radix in a timely manner, and subsequently be terminated.

**Additional context**
Discussed in Teams meeting with @satr and @nilsgstrabo

**Comment by oyron** [comment]
@haakon-bouvet - I'd like to get a better understanding of the need for this. Could you invite me to a 30 min session explaining the scenario and alternative options you have considered?

**Comment by haakon-bouvet** [comment]
> @haakon-bouvet - I'd like to get a better understanding of the need for this. Could you invite me to a 30 min session explaining the scenario and alternative options you have considered?

I have sent you a meeting invitation for today, as I will be out of office all of next week. Hope this works for you.

**Comment by aigelonic** [comment]
@oyron 
Is there a time-frame regarding this enhancement?

Our team is also currently struggling with the same issues regarding running migrations from Radix.
Our current attempt is using the third alternative described above
> Running the script in the docker files entry point - this would potentially cause the API within pod not to respond to Radix in a timely manner, and subsequently be terminated.

However, there are some other issues with this approach that has not been highlighted above:
* Running migrations during startup requires that the final docker image contains the source code, so during the docker build we now need to also copy source-code over to the "production image".
* The startup script is being run by a non-root user (as per recommendation in the Radix documentation), but the migration tool needs _write_ access to the source-folder as it will run build-commands. Thus (parts of?) the source code in the final image will be writable by the non-root user - leading to another security risk IMHO; potential compromised containers will then be able to have total access over the DB, with full migration access.

**Comment by aigelonic** [comment]
The below wall of text is not specific for the pre-deploy-feature, which this issue is all about - but rather a description on the challenges we _currently_ have which we hope that a pre-deploy-step might solve.

---

As requested in the [Slack thread](https://equinor.slack.com/archives/CBKM6N2JY/p1637225150052700), here is a bit more information regarding the source-code "requirements" mentioned earlier.

We are using Entity Framework tools to create and perform migrations, typical this would be something like `dotnet ef database update`. The [documentation](https://docs.microsoft.com/en-us/ef/core/cli/dotnet) on the tool states

> The commands refer to a project and a startup project.

> 
> The project is also known as the target project because it's where the commands add or remove files. By default, the project in the current directory is the target project. You can specify a different project as target project by using the --project option.
> 
> The startup project is the one that the tools build and run. The tools have to execute application code at design time to get information about the project, such as the database connection string and the configuration of the model. By default, the project in the current directory is the startup project. You can specify a different project as startup project by using the --startup-project option.

These are only present in the source and not the final build.

Furthermore, running the tool it perform some operations that requires _write_-access to the source-folder - at least this is the initial errors we are observing. It might this can be circumvented using different output-paths for the tools and is still something that we are testing.

It _might_ be that it is possible to run the migrations tools using the final build artifact with just copying over the project-file rather than the entire source. We have not yet investigated this further.

---

We can also mention that EF6 (the latest version, released quite recently) has a "new" [tool available](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#bundles), called "bundled" for migrations. 
This seems like a possible avenue too which would lead to a pipeline something like (docker-file-steps):
1. Build the application
1. Build a _standalone_ migration bundle
1. Copy build artifacts and migration bundle over to final (docker) layer/image
1. Startup script/entry point applies the migration bundle and then starts up the application.

However, there are some still unclear issues here:
* In step 2. above - creating the bundle - the tooling requires to be logged in Azure - `az login`. Not entirely sure _why_ but I'm guessing it is due to it needs to inspect the current state of the DB and then see which migrations needs to be applied.
If so, this can result in issues promoting between environments as the migration bundle has been created for a specific DB. _However_ it also might be due to it needs to retrieve secrets from a KeyVault - I'm still investigating this 😄 
* Running the migration in the entry point is still prone to the issue mentioned initially: The instance might get killed if the migration takes too long time.

**Comment by oyron** [comment]
@aigelonic - Sorry for the late response. Yes - this has been prioritized and the team har started looking at [Tekton](https://tekton.dev/) for implementing this.

**Comment by aigelonic** [comment]
Again as a side-note:

Our team resolved the current issue regarding migrations by using EF6 and creating "standalone migration bundles" during the build-step, which are run on the Docker entry point. The bundle takes a connection-string as a parameter, so that we are still able to do the promoting between environments.

When the pre-deploy-feature is in place, we can move the running of the migration-bundle from the entry point to to the pre-deploy step, which is more "correct".

**Comment by oyron** [comment]
@aigelonic - This feature is now implemented. See the Radix Slack channel for announcement and info about demo. Closing the issue.
