### ISSUE TITLE
Option of scheduled restart for containers

### ISSUE THREAD

**Issue by ketilbrunequinor** [equinor/radix-platform#562]
In some instances it is desirable to restart containers on a schedule. One example is memory leaks in an application. To mitigate while searching for the root cause it is desirable to have the option to restart the application once memory hits a certain treshold or simply once every hour or day depending on the rate of leakage.

The restart can be done using a timerjob in the application itself, but this will cause downtime on the order of seconds or minutes as the new container is not immediately available. Ideally, the new container should be available immediately and requests would be routed to the new one in a grace period.

In normal kubernetes this would be accomplished using a cron job and commands. Several solutions are described in this stackoverflow thread https://stackoverflow.com/questions/52422300/how-to-schedule-pods-restart.

**Comment by ketilbrunequinor** [comment]
Ideally a yaml property with restartOn: <cron-expression> or <number> for minutes interval would be great.

**Comment by emirgens** [comment]
Added to Radix backlog
Our ref: https://dev.azure.com/Equinor/Radix/_workitems/edit/184106

**Comment by oyron** [comment]
I see that there might be cases when you want to do periodic restarts of your application for a limited period of time. But I do not think this is a feature that will be used frequently. You should be able to accomplish this by setting up a periodic GitHub action calling the restart component endpoint in the Radix API.

Since we believe this feature will be used rarely and there are other ways to handle this, we have decided to not implement this feature. If you have further questions, please comment in the issue or reach out to me directly.
