### ISSUE TITLE
Add support for ignoring Docker image vulnerabilities reported by Snyk

### ISSUE THREAD

**Issue by AtleH** [equinor/radix-platform#704]
**Is your feature request related to a problem? Please describe.**
AFAIK, Radix provides no way to ignore a vulnerability in a Docker image as reported by Snyk. The "Snyk way" of doing this is to provide a `.snyk` file containing the vulnerabilities to be ignored. But Radix does not read this file.

**Describe the solution you'd like**
I would like Radix to honor the ignored vulnerabilities as specified in the `.snyk` file when scanning for vulnerabilities. Supporting this (ignore, un-ignore) through a `.snyk` file will also provide full SDLC support for all changes (traceability, code review, etc).

**Describe alternatives you've considered**
I don't see any alternatives that are of any value. I guess the effect of not supporting this will be that the team "gets used to" the number of vulnerabilities, and over time pays less attention to them.

**Additional context**
Slack discussion: https://equinor.slack.com/archives/CBKM6N2JY/p1656667650771369
Please note that Snyk requires the `--policy-path` option to be specified for this to work: https://github.com/snyk/cli/issues/1164

**Comment by oyron** [comment]
The Snyk container scanner will not be able to read the `.snyk`-file inside the container. We would then have to provide the ignore config to the container scanner somehow, which is a bigger job. Since this feature has not been requested by other teams, it will not be prioritized. Closing the issue. If more teams start asking for this, we will reconsider.
