### ISSUE TITLE
Radix requires deployment key also for public repositories

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/radix-platform#865]
**Is your feature request related to a problem? Please describe.**
Radix requires deployment key also for public repositories

**Describe the solution you'd like**
Radix cloning public repositories without requiring deployment key being set.

**Describe alternatives you've considered**
Still set the Radix suggested deployment key (even though it shouldn't be necessary I think for open source repositories).

**Comment by emirgens** [comment]
Radix ref: [321575](https://dev.azure.com/equinor/Radix/_workitems/edit/321575)

**Comment by oyron** [comment]
Agree, it is not neccessary for open source repositories, and we could implement an exception in web console, back-end and in documentation. But we consider this to have little impact on the users since this is something the users normally do rarely, and we have a lot of feature requests and limited capacity. Hence we will not prioritize this at this point. Closing the issue.
